
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - image: docker.io/jpolidor/chaos-monkey:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: java-app
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault