
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-external-data
  namespace: gatekeeper-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-external-data
  template:
    metadata:
      labels:
        app: opa-external-data
    spec:
      securityContext:
        runAsUser: 65532
      containers:
      - image: docker.io/jpolidor/opa-external-data:latest
        imagePullPolicy: Always
        name: opa-external-data
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: gatekeeper-ca-cert
          mountPath: /tmp/gatekeeper
          readOnly: true
        - name: server-certs
          mountPath: "/etc/tls"
          readOnly: true
        - name: cosign-pub
          mountPath: "/etc/cosign"
          readOnly: true
      volumes:
        - name: gatekeeper-ca-cert
          secret:
            secretName: gatekeeper-webhook-server-cert
            items:
              - key: ca.crt
                path: ca.crt
        - name: server-certs
          secret:
            secretName: server-certs
        - name: cosign-pub
          secret:
            secretName: cosign-pub
---
apiVersion: v1
kind: Service
metadata:
  name: opa-external-data
  namespace: gatekeeper-system
spec:
  ports:
  - port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: opa-external-data